title: Newts
description: "A time-series data store based on Apache Cassandra."
markdown: kramdown
highlighter: rouge
permalink: pretty
timezone: America/Montreal
baseurl: "/newts"
relative_permalinks: false
